### ISSUE TITLE
[Pilotage] Créer un environnement "vide" pilotage formation sur la base de TDB

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#126]

**Comment by antoinebigard** [comment]
@benjaminbarralon  Un peu de délai à prévoir car la stack TDB est pas clean clean. C'est en cours mais après ça va rouler

**Comment by antoinebigard** [comment]
https://pilotage-recette.trajectoirespro.beta.gouv.fr/
