### ISSUE TITLE
Kit pédagogique IJ

### ISSUE THREAD

**Issue by Natouille** [mission-apprentissage/trajectoires-pro#143]

**Comment by Natouille** [comment]
travailler les textes d'accompagnement des indicateurs

**Comment by benjaminbarralon** [comment]
Prendre contact avec Jérémy et houda.said@education.gouv.fr pour création contenu vidéo.

**Comment by Natouille** [comment]
Contact pris, et premier point fait avec Jérémy

**Comment by Natouille** [comment]
Les textes sont disponibles ici https://www.notion.so/mission-apprentissage/Textes-ParcourSup-3e211e2ea3ca47b39a789ab240109b72

**Comment by benjaminbarralon** [comment]
FAQ transmise à PS
