### ISSUE TITLE
Catégoriser la qualité des formations

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#147]
Trouver des grandes catégories de formations par rapport aux 3 indicateurs exposés. Proposer des "slogans" pour proposer des interprétations sur la qualité de ces catégories.

**Comment by Natouille** [comment]
Au vu des remarques d'hier de Jérôme, il faudrait organiser un atelier idéation pour affiner ce qu'on pourra faire sans biaiser qui que ce soit
