### ISSUE TITLE
Des taux régionaux son calculés alors qu'il y a moins de 20 étudiants en année terminale

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#150]

**Comment by antoinebigard** [comment]
Hello @benjaminbarralon Peux tu me re-donner un peu plus de billes stp ? 
Au moins un cas que je puisse vérif

**Comment by benjaminbarralon** [comment]
https://trajectoires-pro.apprentissage.beta.gouv.fr/api/inserjeunes/regionales/52/certifications/46321219
https://trajectoires-pro.apprentissage.beta.gouv.fr/api/inserjeunes/regionales/75/certifications/46321004
https://trajectoires-pro.apprentissage.beta.gouv.fr/api/inserjeunes/regionales/44/certifications/32025416

**Comment by benjaminbarralon** [comment]
Valable à priori en voie app et sco
