### ISSUE TITLE
Etude de l'historique des CFD

### ISSUE THREAD

**Issue by jadynekena** [mission-apprentissage/trajectoires-pro#154]
# Il existe 4 cas de changements de CFD:
1. le CFD historique est **fermé et non remplacé** (à voir comment cela peut s'identifier?)
2. le CFD historique est fermé et remplacé:
     - par 1 CFD unique : **1 à 1**
     - par 1 CFD commun à d'autres CFD historiques : **fusion**
     - par plusieurs CFD : **split**
 
L'objectif est d'évaluer la part des changements 1 CFD à 1 CFD, qui est intimement lié aux [bugs de l'ONISEP](https://github.com/mission-apprentissage/trajectoires-pro/issues/144).

A noter que les changements CFD impactent les 2 voies sur IJ:
- **en apprentissage**: le CFD est utilisé 
- **en voie pro**: le MEFSTAT11 déduit par le CFD est utilisé

On peut déjà utiliser la [BCN](https://infocentre.pleiade.education.fr/bcn/search) et la [table de correspondance](https://tables-correspondances.apprentissage.beta.gouv.fr/api/v1/docs/#/Outils/post_cfd) pour comprendre les changements.

Une piste serait également de : 
- contacter Anne Becquet pour mieux comprendre l'historique des CFD
- contacter l'ONISEP pour discuter des subtilités de ces changements

**Comment by antoinebigard** [comment]
<3
