### ISSUE TITLE
[Widget] décalage logo InserJeunes

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#17]
Pour les widgets horizontaux et verticaux, le logo InserJeunes apparait décalé dans l'entête.

![image](https://user-images.githubusercontent.com/72451547/166892846-ef5d2b00-fd3b-4c1e-a64f-4f827196f228.png)

![image](https://user-images.githubusercontent.com/72451547/166892907-42013479-13af-4dd4-857e-ebd2b5012f9f.png)

**Comment by ericplaquevent** [comment]
On dirait que la police Marianne n'est pas chargée aussi. Tu es sûr quel navigateur / OS ?

**Comment by ericplaquevent** [comment]
@benjaminbarralon en fait ça correspond au Figma sur l'[itération 10 et 12](https://www.figma.com/file/zv9lV0YyMYRepHZIAnnnKx/Trajectoires-Pros?node-id=152%3A300). À voir ensemble quelle version on implémente :slightly_smiling_face:

**Comment by ericplaquevent** [comment]
À voir aussi si on peut récupérer une version SVG du logo InserJeunes
