### ISSUE TITLE
[Widget] Retour "Not found"

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#18]
Le widget retourne `Not Found` dans ces 2 cas:

- L'UAI et ou le code formation ne sont pas connus
- Le Taux d'emploi et la Poursuite d'étude ne sont pas disponibles (couple UAI/code formation valide)

Spécifier les message retour en fonction de ces 2 cas:

- UAI ou code formation invalides
- Donnée non disponible

**Comment by ericplaquevent** [comment]
@benjaminbarralon 
pour le premier cas j'ai mis `UAI, code formation et/ou millésime invalide` car le millésime aussi peut-être inconnu. Ça te va ? N'hésite pas à proposer un autre wording :slightly_smiling_face:

**Comment by benjaminbarralon** [comment]
Wording ok pour moi.

**Comment by bguerout** [comment]
Est ce qu'on ne prévoirait plutôt pas une image lorsque les données ne sont pas disponibles ou carrément une image vide ? #22

**Comment by benjaminbarralon** [comment]
Je pense qu'il faut discuter de ce sujet avec ceux qui vont intégrer le widget notamment l'ONISEP (image vs texte). La distinction des 2 cas était utile pour les tests.
