### ISSUE TITLE
[API] Correspondance CFD

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#19]
Dans les données IJ un certain nombre de CFD (partie apprentissage) ne sont pas ou plus valides (cf. csv).

[CFD IJ invalid.csv](https://github.com/mission-apprentissage/trajectoires-pro/files/8630307/formation_catalogue_by_CFD_joined_empty.1.csv)

Utiliser https://tables-correspondances.apprentissage.beta.gouv.fr/api/v1/docs/ pour prendre en compte les code actualisé et que les requêtes retourne les données correspondantes.

Exemple: Une requête UAI: 0212220Z, CFD: 46033104 (valide), permet de renvoyer les données IJ correspondant à UAI: 0212220Z , CFD: 56033102 (obsolète)

**Comment by benjaminbarralon** [comment]
Peut-on le tester?

**Comment by bguerout** [comment]
Suite à nos discussions, nous avons décidé d'exporter un fichier des stats de certification avec la date de fermeture du code certification s'il est fermé.
