### ISSUE TITLE
[API] Documenter l'API (swagger)

### ISSUE THREAD

**Issue by benjaminbarralon** [mission-apprentissage/trajectoires-pro#33]

**Comment by bguerout** [comment]
On pourrait d'ailleurs utiliser un autre outil que Swagger qui est, je trouve assez peu lisible.

**Comment by benjaminbarralon** [comment]
Pas de préférence pour l'outil. C'est plus une question d'homogénéité avec les autres produits de la mission. Je mentionnais swagger plus à titre d'exemple.
